// AUTO-GENERATED by scripts/build-deck-params.mjs — 勿手改
export const deckCues: { start: number; end: number; text: string }[] = [
  { start: 0, end: 3.8, text: "这是示例第一页的字幕。" },
  { start: 4.2, end: 8, text: "示例第二页,替换 deck-scenes 后生效。" },
];
