// AUTO-GENERATED by scripts/build-deck-params.mjs — 换素材/稿/配音后重跑，勿手改
export const deckParams = {
  fps: 30, width: 1920, height: 1080, overlapSeconds: 0,
  pages: [
    { index: 1, start: 0, audioSeconds: 3.8, pageSeconds: 4.2 },
    { index: 2, start: 4.2, audioSeconds: 3.8, pageSeconds: 4.2 },
  ],
  totalSeconds: 8.4,
} as const;
