// AUTO-GENERATED by tools/gen-cues.mjs — 改 EDL 或注解后重跑，勿手改
export interface TitleCardCue { t: number; ttl: number; kicker: string; title: string; sub: string; }
export interface ChapterCardCue { t: number; ttl: number; index: string; name: string; }
export interface NameBannerCue { t: number; ttl: number; name: string; tag: string; }
export interface DamageCardCue { t: number; ttl: number; value: string; label: string; }
export interface EndCardCue { t: number; ttl: number; title: string; rows: { label: string; value: string }[]; sub: string; }
export interface SubtitleCue { start: number; end: number; text: string; }
export interface DataBarGroup { t: number; ttl?: number; x: number; y: number; scale?: number; bars: { label: string; value: number; unit?: string; color?: string }[]; }
export interface SpotlightCue { t: number; ttl: number; kind: 'circle' | 'arrow' | 'box'; x: number; y: number; w: number; h: number; text?: string; }

export const MAIN_TOTAL = 168.20;
export const hsrCues = {
  subtitles: [
  {
    "start": 5.4,
    "end": 7.4,
    "text": "货币战争：星穹铁道的自走棋"
  },
  {
    "start": 7.5,
    "end": 9.4,
    "text": "攒钱、上人口、凑完全体"
  },
  {
    "start": 10,
    "end": 11.8,
    "text": "决战前夕，先把板子理顺"
  },
  {
    "start": 11.8,
    "end": 13.4,
    "text": "今晚的目标：三星昔涟、三星银狼"
  },
  {
    "start": 13.9,
    "end": 16,
    "text": "合成三星的奖励：金币雨"
  },
  {
    "start": 16.3,
    "end": 18.9,
    "text": "刷牌：把钱换成战力"
  },
  {
    "start": 19.2,
    "end": 21.8,
    "text": "每一轮商店都是一次机会"
  },
  {
    "start": 22.3,
    "end": 24.9,
    "text": "拿牌、囤钱，两手都要抓"
  },
  {
    "start": 28.4,
    "end": 31.4,
    "text": "中期运营：板面一点点厚起来"
  },
  {
    "start": 31.6,
    "end": 34.8,
    "text": "三星在路上，谁先成型谁说了算"
  },
  {
    "start": 35,
    "end": 39.6,
    "text": "备战阶段的每一秒都是钱"
  },
  {
    "start": 40.4,
    "end": 43.8,
    "text": "时间快进：半小时运营压缩成十几秒"
  },
  {
    "start": 44,
    "end": 47.6,
    "text": "主力一张张到齐，装备一件件穿上"
  },
  {
    "start": 47.8,
    "end": 51.8,
    "text": "板面成型，只差最后一步"
  },
  {
    "start": 52,
    "end": 56.2,
    "text": "决战前的家底，全攒齐了"
  },
  {
    "start": 57.1,
    "end": 59.5,
    "text": "然后，银狼塞过来一个好东西"
  },
  {
    "start": 59.7,
    "end": 62.9,
    "text": "GM 操作台：加金币、满血、改敌人血量"
  },
  {
    "start": 63.1,
    "end": 67.1,
    "text": "字面意义上的，开挂菜单"
  },
  {
    "start": 68,
    "end": 70.4,
    "text": "敌方生命值：自己定"
  },
  {
    "start": 70.6,
    "end": 73.1,
    "text": "拉到 1000%，嫌它不够肉"
  },
  {
    "start": 73.8,
    "end": 76.2,
    "text": "确认——不作弊，不痛快"
  },
  {
    "start": 76.9,
    "end": 80.1,
    "text": "回头把最后的三星合出来"
  },
  {
    "start": 80.8,
    "end": 82.8,
    "text": "合成光效，看着就爽"
  },
  {
    "start": 83.5,
    "end": 85.7,
    "text": "13/13，人口拉满"
  },
  {
    "start": 85.8,
    "end": 87.8,
    "text": "970 金币，全是运营攒下的"
  },
  {
    "start": 88.4,
    "end": 90.4,
    "text": "商店直接刷出三星卡"
  },
  {
    "start": 90.4,
    "end": 92.4,
    "text": "后台清一色，全是三星"
  },
  {
    "start": 92.9,
    "end": 94.9,
    "text": "又一张三星，拿下"
  },
  {
    "start": 94.9,
    "end": 96.9,
    "text": "昔涟、银狼，一个都不能少"
  },
  {
    "start": 97.3,
    "end": 100.7,
    "text": "三星到手，决战就绪"
  },
  {
    "start": 101.4,
    "end": 104.6,
    "text": "财富遗物：决战前最后一块拼图"
  },
  {
    "start": 105.5,
    "end": 107.7,
    "text": "决战阵容，检查完毕"
  },
  {
    "start": 107.8,
    "end": 109.8,
    "text": "对面血量 1000%，来吧"
  },
  {
    "start": 110.4,
    "end": 112.4,
    "text": "战斗阶段 3-7"
  },
  {
    "start": 112.4,
    "end": 114.7,
    "text": "首领强敌，来袭"
  },
  {
    "start": 115.4,
    "end": 117.4,
    "text": "第一轮齐射，21 亿起步"
  },
  {
    "start": 117.4,
    "end": 119.3,
    "text": "这还只是热身"
  },
  {
    "start": 119.9,
    "end": 123.1,
    "text": "大招，连环开"
  },
  {
    "start": 124,
    "end": 126.6,
    "text": "完整体演出，一个接一个"
  },
  {
    "start": 126.8,
    "end": 129.2,
    "text": "伤害？先别急"
  },
  {
    "start": 129.9,
    "end": 131.7,
    "text": "蓄力——"
  },
  {
    "start": 131.7,
    "end": 133.3,
    "text": "幸运暴击，10 亿起步"
  },
  {
    "start": 133.8,
    "end": 136.2,
    "text": "单段伤害，直接破万亿"
  },
  {
    "start": 137.1,
    "end": 139.7,
    "text": "昔涟完整体，温柔登场"
  },
  {
    "start": 139.9,
    "end": 144.1,
    "text": "这一段，一个字都不用多说"
  },
  {
    "start": 144.9,
    "end": 147.1,
    "text": "伤害结算：5566 亿暴击"
  },
  {
    "start": 147.3,
    "end": 151.5,
    "text": "对面血量 1000%？没感觉到"
  },
  {
    "start": 152.4,
    "end": 155.6,
    "text": "然后，数字直接上万亿"
  },
  {
    "start": 156.4,
    "end": 158.6,
    "text": "真伤结算，1622 亿一跳"
  },
  {
    "start": 158.8,
    "end": 161.2,
    "text": "血条？什么血条？"
  },
  {
    "start": 161.7,
    "end": 163.5,
    "text": "第一次运营，完美收官"
  }
] as SubtitleCue[],
  titleCards: [
  {
    "t": 0.6,
    "ttl": 3.9,
    "kicker": "崩坏：星穹铁道 · 货币战争",
    "title": "第一次三星昔涟银狼",
    "sub": "这把，直接爽局"
  }
] as TitleCardCue[],
  chapterCards: [
  {
    "t": 5,
    "ttl": 1.8,
    "index": "PHASE 1",
    "name": "运营"
  },
  {
    "t": 56.5,
    "ttl": 1.8,
    "index": "PHASE 2",
    "name": "开挂时间"
  },
  {
    "t": 105,
    "ttl": 1.8,
    "index": "FINAL",
    "name": "决战 3-7"
  }
] as ChapterCardCue[],
  nameBanners: [
  {
    "t": 57.7,
    "ttl": 3,
    "name": "银狼999",
    "tag": "这个好东西是她给的"
  },
  {
    "t": 137.5,
    "ttl": 3.2,
    "name": "昔涟 · 完整体",
    "tag": "完整体登场"
  }
] as NameBannerCue[],
  damageCards: [
  {
    "t": 134.1,
    "ttl": 2.2,
    "value": "1.2 万亿",
    "label": "单次爆发伤害"
  },
  {
    "t": 145.1,
    "ttl": 2.2,
    "value": "5566 亿",
    "label": "幸运暴击"
  },
  {
    "t": 152.8,
    "ttl": 2.6,
    "value": "9999 亿",
    "label": "单段伤害 · 打满上限"
  }
] as DamageCardCue[],
  spotlights: [
  {
    "t": 58.7,
    "ttl": 3.4,
    "kind": "box",
    "x": 380,
    "y": 320,
    "w": 1120,
    "h": 430,
    "text": "GM 操作台"
  },
  {
    "t": 68.3,
    "ttl": 2.6,
    "kind": "box",
    "x": 600,
    "y": 470,
    "w": 740,
    "h": 130,
    "text": "敌人血量 1000%"
  },
  {
    "t": 83.8,
    "ttl": 2.8,
    "kind": "box",
    "x": 1655,
    "y": 860,
    "w": 200,
    "h": 105,
    "text": "970 金币"
  }
] as SpotlightCue[],
  dataBars: [
  {
    "t": 83.4,
    "ttl": 7,
    "x": 110,
    "y": 600,
    "scale": 0.9,
    "bars": [
      {
        "label": "备战开局",
        "value": 62,
        "unit": "金",
        "color": "#e8c15a"
      },
      {
        "label": "峰值(加金币)",
        "value": 1029,
        "unit": "金",
        "color": "#f2984a"
      },
      {
        "label": "决战前",
        "value": 970,
        "unit": "金",
        "color": "#7bc96f"
      }
    ]
  }
] as DataBarGroup[],
  endCard: {
  "t": 164,
  "ttl": 4,
  "title": "三星昔涟银狼 · 爽局收官",
  "rows": [
    {
      "label": "单段伤害上限",
      "value": "9999 亿（幸运暴击）"
    },
    {
      "label": "单角色总伤",
      "value": "343 亿+（霸绊面板）"
    },
    {
      "label": "本局配置",
      "value": "敌人血量 1000% · 人口 13/13"
    }
  ],
  "sub": "下一把，已经预约"
} as EndCardCue,
  darkRanges: [{ from: 0, to: 168.20 }],
};

export const VERTICAL_TOTAL = 42.50;
export const hsrCuesVertical = {
  titleCards: [
  {
    "t": 0.25,
    "ttl": 2.3,
    "kicker": "货币战争 · 第一次三星昔涟银狼",
    "title": "直接爽局",
    "sub": ""
  }
] as TitleCardCue[],
  subtitles: [
  {
    "start": 3.1,
    "end": 5.7,
    "text": "银狼塞来一个 GM 操作台"
  },
  {
    "start": 5.9,
    "end": 8.6,
    "text": "加金币、满血、改血量，随便开"
  },
  {
    "start": 9.1,
    "end": 11.7,
    "text": "完整体演出，直接拉满"
  },
  {
    "start": 15.3,
    "end": 17.5,
    "text": "昔涟完整体"
  },
  {
    "start": 17.7,
    "end": 20.1,
    "text": "先看这段演出"
  },
  {
    "start": 20.3,
    "end": 22.5,
    "text": "伤害？等下再说"
  },
  {
    "start": 23.1,
    "end": 25.1,
    "text": "幸运暴击：5566 亿"
  },
  {
    "start": 25.2,
    "end": 27.1,
    "text": "这还只是一段"
  },
  {
    "start": 27.6,
    "end": 31,
    "text": "数字，上万亿了"
  },
  {
    "start": 31.6,
    "end": 34,
    "text": "真伤 1622 亿一跳"
  },
  {
    "start": 34.2,
    "end": 36.6,
    "text": "对面血量 1000%，照样秒"
  },
  {
    "start": 37,
    "end": 38.8,
    "text": "挑战成功"
  }
] as SubtitleCue[],
  damageCards: [
  {
    "t": 23.2,
    "ttl": 1.9,
    "value": "5566 亿",
    "label": "幸运暴击"
  },
  {
    "t": 27.8,
    "ttl": 2.4,
    "value": "9999 亿",
    "label": "单段上限"
  }
] as DamageCardCue[],
  endCard: {
  "t": 39.3,
  "ttl": 2.9,
  "title": "三星昔涟银狼 · 爽局",
  "rows": [
    {
      "label": "单段上限",
      "value": "9999 亿"
    },
    {
      "label": "敌方血量",
      "value": "1000%"
    }
  ],
  "sub": "完整版已发布"
} as EndCardCue,
};
