// AUTO-GENERATED by scripts/build-deck-params.mjs — 换素材/稿/配音后重跑，勿手改
export const deckParams = {
  fps: 30, width: 1920, height: 1080, overlapSeconds: 0.5,
  pages: [
    { index: 1, start: 0, audioSeconds: 12.546, pageSeconds: 12.946 },
    { index: 2, start: 12.946, audioSeconds: 14.06, pageSeconds: 14.46 },
    { index: 3, start: 27.406, audioSeconds: 12.226, pageSeconds: 12.626 },
    { index: 4, start: 40.032, audioSeconds: 13.555, pageSeconds: 13.955 },
    { index: 5, start: 53.987, audioSeconds: 13.086, pageSeconds: 13.486 },
    { index: 6, start: 67.473, audioSeconds: 13.716, pageSeconds: 14.116 },
    { index: 7, start: 81.589, audioSeconds: 9.606, pageSeconds: 10.006 },
    { index: 8, start: 91.595, audioSeconds: 9.746, pageSeconds: 10.146 },
    { index: 9, start: 101.741, audioSeconds: 8.597, pageSeconds: 8.997 },
    { index: 10, start: 110.738, audioSeconds: 9.532, pageSeconds: 9.932 },
  ],
  totalSeconds: 121.17,
} as const;
