// 用 ffprobe 读取素材规格（分辨率/帧率/总时长），生成 src/footage-params.ts —— 让正片输出参数随素材自动适配（不写死）。
// Usage: node scripts/probe-footage.mjs [footagePath]   （默认 public/footage.mp4）
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const footage = process.argv[2] ?? join(root, "public", "footage.mp4");

const out = execFileSync(
  "ffprobe",
  [
    "-v",
    "error",
    "-select_streams",
    "v:0",
    "-show_entries",
    "stream=width,height,r_frame_rate:format=duration",
    "-of",
    "json",
    footage,
  ],
  { encoding: "utf8" },
);

const info = JSON.parse(out);
const stream = info.streams[0];
if (!stream?.width || !stream?.height || !stream?.r_frame_rate) {
  console.error("probe failed: incomplete stream info from ffprobe");
  process.exit(1);
}

const [num, den] = stream.r_frame_rate.split("/").map(Number);
const fps = Math.round((num / den) * 100) / 100; // 59.94 这类分数帧率保留两位

// format.duration 是字符串秒数；个别容器拿不到（undefined/N/A）时跳过时长字段，不阻断分辨率产出
const durationSeconds = Number(info.format?.duration);
const durationInFrames = Number.isFinite(durationSeconds) ? Math.round(durationSeconds * fps) : null;

const ts = `// AUTO-GENERATED by scripts/probe-footage.mjs — 换素材后重跑该脚本，勿手改
export const footageParams = { width: ${stream.width}, height: ${stream.height}, fps: ${fps}${durationInFrames !== null ? `, durationInFrames: ${durationInFrames}` : ""} } as const;
`;
writeFileSync(join(root, "src", "footage-params.ts"), ts);

console.log(
  `footage: ${stream.width}x${stream.height} @ ${fps}fps${durationInFrames !== null ? `, ${durationInFrames} frames` : ""} -> src/footage-params.ts`,
);
