// AUTO-GENERATED by scripts/build-deck-params.mjs — 换素材/稿/配音后重跑，勿手改
export const deckParams = {
  fps: 30, width: 1920, height: 1080, overlapSeconds: 0,
  pages: [
    { index: 1, start: 0, audioSeconds: 7.312, pageSeconds: 7.712 },
    { index: 2, start: 7.712, audioSeconds: 8.967, pageSeconds: 9.367 },
    { index: 3, start: 17.079, audioSeconds: 8.737, pageSeconds: 9.137 },
    { index: 4, start: 26.216, audioSeconds: 12.661, pageSeconds: 13.061 },
    { index: 5, start: 39.277, audioSeconds: 11.391, pageSeconds: 11.791 },
    { index: 6, start: 51.068, audioSeconds: 10.641, pageSeconds: 11.041 },
    { index: 7, start: 62.109, audioSeconds: 12.816, pageSeconds: 13.216 },
    { index: 8, start: 75.325, audioSeconds: 11.081, pageSeconds: 11.481 },
    { index: 9, start: 86.806, audioSeconds: 7.747, pageSeconds: 8.147 },
    { index: 10, start: 94.953, audioSeconds: 6.782, pageSeconds: 7.182 },
    { index: 11, start: 102.135, audioSeconds: 7.033, pageSeconds: 7.433 },
  ],
  totalSeconds: 109.568,
} as const;
